apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: LoadBalancer  # Menggunakan LoadBalancer untuk akses eksternal
  ports:
    - port: 80  # Port yang akan digunakan untuk akses
      targetPort: 80  # Port yang diekspos di container
  selector:
    app: php-app  # Harus cocok dengan label pada deployment
