apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1  # Jumlah pod yang ingin dijalankan
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: pmerta22/deploy-php:latest  # Ganti dengan nama image PHP kamu
        ports:
        - containerPort: 80  # Port yang diekspos di container
        env:
        - name: DB_HOST
          value: "mysql-service"  # Nama service MySQL
        - name: DB_USER
          value: "Admin"  # Sesuaikan dengan MYSQL_USER dari MySQL
        - name: DB_PASSWORD
          value: "1234"  # Sesuaikan dengan MYSQL_PASSWORD dari MySQL
        - name: DB_NAME
          value: "Smart_temple"  # Sesuaikan dengan MYSQL_DATABASE dari MySQL
